//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fujitsu.SLM.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fujitsu.SLM.Web.Resources.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User is still the owner of a customer.  Please change customer ownership details prior to deletion..
        /// </summary>
        public static string ArchitectIsStillCustomerOwner {
            get {
                return ResourceManager.GetString("ArchitectIsStillCustomerOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string CannotFindReferenceDataItemToBeDeleted {
            get {
                return ResourceManager.GetString("CannotFindReferenceDataItemToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contributor record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string ContributorCannotBeFound {
            get {
                return ResourceManager.GetString("ContributorCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Version Number must be greater than the current Version Number.
        /// </summary>
        public static string CustomerAuditVersionNumber {
            get {
                return ResourceManager.GetString("CustomerAuditVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all Service Desks belonging to this Customer prior to deletion..
        /// </summary>
        public static string CustomerCannotBeDeletedDueToServiceDesksExisting {
            get {
                return ResourceManager.GetString("CustomerCannotBeDeletedDueToServiceDesksExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string CustomerCannotFindCustomerToBeDeleted {
            get {
                return ResourceManager.GetString("CustomerCannotFindCustomerToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer record to be updated does not exist. Please refresh the page and try again..
        /// </summary>
        public static string CustomerCannotFindCustomerToBeUpdated {
            get {
                return ResourceManager.GetString("CustomerCannotFindCustomerToBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Pack cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string CustomerPackCannotBeFound {
            get {
                return ResourceManager.GetString("CustomerPackCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer..
        /// </summary>
        public static string CustomerPleaseSelect {
            get {
                return ResourceManager.GetString("CustomerPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select --.
        /// </summary>
        public static string DefaultDropDownListText {
            get {
                return ResourceManager.GetString("DefaultDropDownListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Desk Input Type must be selected..
        /// </summary>
        public static string DeskInputTypesAtLeastOne {
            get {
                return ResourceManager.GetString("DeskInputTypesAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Diagram cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string DiagramCannotBeFound {
            get {
                return ResourceManager.GetString("DiagramCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Domain Type..
        /// </summary>
        public static string DomainTypePleaseSelect {
            get {
                return ResourceManager.GetString("DomainTypePleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be unique..
        /// </summary>
        public static string EntityNameIsNotUnique {
            get {
                return ResourceManager.GetString("EntityNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred the details of which have been logged.Please try again and if the problem persists, contact an administrator with the Error ID [{0}].
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Function Type..
        /// </summary>
        public static string FunctionTypePleaseSelect {
            get {
                return ResourceManager.GetString("FunctionTypePleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file supplied is not a valid content type..
        /// </summary>
        public static string InvalidContentType {
            get {
                return ResourceManager.GetString("InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file supplied has no content..
        /// </summary>
        public static string NoFileContent {
            get {
                return ResourceManager.GetString("NoFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a spreadsheet file to import..
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Template Type has been specified on the template import..
        /// </summary>
        public static string NoTemplateTypeSelected {
            get {
                return ResourceManager.GetString("NoTemplateTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter is of type &apos;System&apos; and cannot be updated from the UI..
        /// </summary>
        public static string ParametersParameterIsSystem {
            get {
                return ResourceManager.GetString("ParametersParameterIsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all references to this {0} prior to deletion..
        /// </summary>
        public static string ReferenceDataItemIsStillUtilised {
            get {
                return ResourceManager.GetString("ReferenceDataItemIsStillUtilised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Region field is required..
        /// </summary>
        public static string RegionFieldIsRequired {
            get {
                return ResourceManager.GetString("RegionFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Service Components have been specified. A Service Component can only have a single Resolver Type, Resolver Group and Service Delivery unit.. Please correct and try again..
        /// </summary>
        public static string ResolverAddDuplicateServiceComponent {
            get {
                return ResourceManager.GetString("ResolverAddDuplicateServiceComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove any dependents belonging to the Resolver Group prior to deletion..
        /// </summary>
        public static string ResolverCannotBeDeletedDueToDependents {
            get {
                return ResourceManager.GetString("ResolverCannotBeDeletedDueToDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Resolver Group cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string ResolverGroupCannotBeFound {
            get {
                return ResourceManager.GetString("ResolverGroupCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Resolver Group must be specified when Operational Process Types are added..
        /// </summary>
        public static string ResolverMustHaveResolverGroupForOperationalProcesses {
            get {
                return ResourceManager.GetString("ResolverMustHaveResolverGroupForOperationalProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Resolver Group must be specified for a Service Activity to be added..
        /// </summary>
        public static string ResolverMustHaveResolverGroupForServiceActivity {
            get {
                return ResourceManager.GetString("ResolverMustHaveResolverGroupForServiceActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Desk is required..
        /// </summary>
        public static string ResolverSerivceDeskMandatory {
            get {
                return ResourceManager.GetString("ResolverSerivceDeskMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Delivery Organisation is required..
        /// </summary>
        public static string ResolverServiceDeliveryOrgMandatory {
            get {
                return ResourceManager.GetString("ResolverServiceDeliveryOrgMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Desk is required..
        /// </summary>
        public static string ResolverServiceDeskMandatory {
            get {
                return ResourceManager.GetString("ResolverServiceDeskMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale factor is used to scale the diagram into the appropriate content (for example, PDF, Image file, or SVG for Visio).  If the diagram does not fit within the chosen export format please reduce the scale accordingly..
        /// </summary>
        public static string ScaleFactor {
            get {
                return ResourceManager.GetString("ScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Level 1 Service Components have been specified. A Level 1 Service Component can only have a single child. Please correct and try again..
        /// </summary>
        public static string ServiceComponentAddDuplicateParent {
            get {
                return ResourceManager.GetString("ServiceComponentAddDuplicateParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Service Component already has child. Please referesh the page and try again..
        /// </summary>
        public static string ServiceComponentAlreadyHasChild {
            get {
                return ResourceManager.GetString("ServiceComponentAlreadyHasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove Level 2 Service Component (if Level 1) and/or Resolver belonging to this Service Component prior to deletion..
        /// </summary>
        public static string ServiceComponentCannotBeDeletedDueToDependents {
            get {
                return ResourceManager.GetString("ServiceComponentCannotBeDeletedDueToDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Component cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string ServiceComponentCannotBeFound {
            get {
                return ResourceManager.GetString("ServiceComponentCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all Service Activities and Operational Processes belonging to this Resolver Group before deletion..
        /// </summary>
        public static string ServiceComponentCannotDeleteResolverGroup {
            get {
                return ResourceManager.GetString("ServiceComponentCannotDeleteResolverGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Component cannot be found and may have been changed by somebody else. Please click Return and retry editing..
        /// </summary>
        public static string ServiceComponentEditCannotBeFound {
            get {
                return ResourceManager.GetString("ServiceComponentEditCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Component Name (Level 2)&apos; must not be empty..
        /// </summary>
        public static string ServiceComponentEditChildComponentMustBeSupplied {
            get {
                return ResourceManager.GetString("ServiceComponentEditChildComponentMustBeSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Component is not in the expected state and may have been changed by somebody else. Please click Return and retry editing..
        /// </summary>
        public static string ServiceComponentIncorrectState {
            get {
                return ResourceManager.GetString("ServiceComponentIncorrectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Component Level is invalid. Please click Return and retry editing..
        /// </summary>
        public static string ServiceComponentLevelInvalid {
            get {
                return ResourceManager.GetString("ServiceComponentLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Component Level..
        /// </summary>
        public static string ServiceComponentLevelPleaseSelect {
            get {
                return ResourceManager.GetString("ServiceComponentLevelPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Service Component..
        /// </summary>
        public static string ServiceComponentPleaseSelect {
            get {
                return ResourceManager.GetString("ServiceComponentPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Resolver must have a Service Delivery Organisation (SDO) type..
        /// </summary>
        public static string ServiceComponentServiceDeliveryOrganisationTypeIdMustBeSupplied {
            get {
                return ResourceManager.GetString("ServiceComponentServiceDeliveryOrganisationTypeIdMustBeSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Delivery Unit (SDU) notes cannot be supplied without first selecting an SDU..
        /// </summary>
        public static string ServiceComponentServiceDeliveryUnitTypeIdMustBeSupplied {
            get {
                return ResourceManager.GetString("ServiceComponentServiceDeliveryUnitTypeIdMustBeSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Decomposition record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string ServiceDecompositionCannotFindServiceDecompositionToBeDeleted {
            get {
                return ResourceManager.GetString("ServiceDecompositionCannotFindServiceDecompositionToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all Service Desks and/or Service Domains belonging to this Service Decomposition prior to deletion..
        /// </summary>
        public static string ServiceDecompositionsCannotBeDeletedDueToServiceDesksAndOrServiceDomainsExisting {
            get {
                return ResourceManager.GetString("ServiceDecompositionsCannotBeDeletedDueToServiceDesksAndOrServiceDomainsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Desk record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string ServiceDeskCannotFindServiceDeskToBeDeleted {
            get {
                return ResourceManager.GetString("ServiceDeskCannotFindServiceDeskToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Service Desk..
        /// </summary>
        public static string ServiceDeskPleaseSelect {
            get {
                return ResourceManager.GetString("ServiceDeskPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all Service Domains belonging to this Service Desk prior to deletion..
        /// </summary>
        public static string ServiceDesksCannotBeDeletedDueToServiceDomainsExisting {
            get {
                return ResourceManager.GetString("ServiceDesksCannotBeDeletedDueToServiceDomainsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all Functions belonging to this Service Domain prior to deletion..
        /// </summary>
        public static string ServiceDomainCannotBeDeletedDueToFunctionsExisting {
            get {
                return ResourceManager.GetString("ServiceDomainCannotBeDeletedDueToFunctionsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Domain cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string ServiceDomainCannotBeFound {
            get {
                return ResourceManager.GetString("ServiceDomainCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Domain record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string ServiceDomainCannotFindDomainToBeDeleted {
            get {
                return ResourceManager.GetString("ServiceDomainCannotFindDomainToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Service Domain..
        /// </summary>
        public static string ServiceDomainPleaseSelect {
            get {
                return ResourceManager.GetString("ServiceDomainPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all Components belonging to this Service Function prior to deletion..
        /// </summary>
        public static string ServiceFunctionCannotBeDeletedDueToComponentsExisitng {
            get {
                return ResourceManager.GetString("ServiceFunctionCannotBeDeletedDueToComponentsExisitng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Function cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string ServiceFunctionCannotBeFound {
            get {
                return ResourceManager.GetString("ServiceFunctionCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Function record to be deleted does not exist. Please refresh the page and try again..
        /// </summary>
        public static string ServiceFunctionCannotFindFunctionToBeDeleted {
            get {
                return ResourceManager.GetString("ServiceFunctionCannotFindFunctionToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Service Function..
        /// </summary>
        public static string ServiceFunctionPleaseSelect {
            get {
                return ResourceManager.GetString("ServiceFunctionPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a unique Fujitsu email address..
        /// </summary>
        public static string TooltipEmail {
            get {
                return ResourceManager.GetString("TooltipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a password with at least 6 characters, containing a minimum of one digit, one lowercase character and one uppercase character..
        /// </summary>
        public static string TooltipPasswordComplexityRules {
            get {
                return ResourceManager.GetString("TooltipPasswordComplexityRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User cannot be found. Please refresh the page and try again..
        /// </summary>
        public static string UserCannotFindUser {
            get {
                return ResourceManager.GetString("UserCannotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a User..
        /// </summary>
        public static string UserPleaseSelect {
            get {
                return ResourceManager.GetString("UserPleaseSelect", resourceCulture);
            }
        }
    }
}
