//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fujitsu.SLM.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fujitsu.SLM.Data.DatabaseResources", typeof(DatabaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 26/02/2015
        ///-- Description:	Customer Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteCustomer]
        ///	-- Add the parameters for the stored procedure here
        ///	@CustomerId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN TRAN
        ///
        ///		DECLARE @ServiceDeskId int
        ///		DECLARE ServiceDesk_cursor CUR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteCustomer {
            get {
                return ResourceManager.GetString("Create_spDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Resolver Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteResolver]
        ///	-- Add the parameters for the stored procedure here
        ///	@ResolverId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///	BEGIN
        ///
        ///	DELETE FROM [dbo].[OperationalProcessType]
        ///		WHERE Resolver_Id = @R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteResolver {
            get {
                return ResourceManager.GetString("Create_spDeleteResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Service Component Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteServiceComponent]
        ///	-- Add the parameters for the stored procedure here
        ///	@ServiceComponentId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN
        ///		DECLARE @ComponentId int
        ///		DECLARE Servic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteServiceComponent {
            get {
                return ResourceManager.GetString("Create_spDeleteServiceComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Service Desk Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteServiceDesk]
        ///	-- Add the parameters for the stored procedure here
        ///	@ServiceDeskId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN
        ///
        ///		DECLARE @ResolverId int
        ///		DECLARE Resolver_cursor CURS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteServiceDesk {
            get {
                return ResourceManager.GetString("Create_spDeleteServiceDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Service Desk Content Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteServiceDeskContents]
        ///	-- Add the parameters for the stored procedure here
        ///	@ServiceDeskId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN
        ///
        ///		DECLARE @ResolverId int
        ///		DECLARE Reso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteServiceDeskContents {
            get {
                return ResourceManager.GetString("Create_spDeleteServiceDeskContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Service Domain Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteServiceDomain]
        ///	-- Add the parameters for the stored procedure here
        ///	@ServiceDomainId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN
        ///		DECLARE @FunctionId int
        ///		DECLARE Function_cursor  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteServiceDomain {
            get {
                return ResourceManager.GetString("Create_spDeleteServiceDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Service Function Deletion
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[spDeleteServiceFunction]
        ///	-- Add the parameters for the stored procedure here
        ///	@ServiceFunctionId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN
        ///		DECLARE @ComponentId int
        ///		DECLARE Component [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_spDeleteServiceFunction {
            get {
                return ResourceManager.GetString("Create_spDeleteServiceFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteCustomer]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[spDeleteCustomer]
        ///GO
        ///.
        /// </summary>
        internal static string Drop_spDeleteCustomer {
            get {
                return ResourceManager.GetString("Drop_spDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteResolver]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[spDeleteResolver]
        ///.
        /// </summary>
        internal static string Drop_spDeleteResolver {
            get {
                return ResourceManager.GetString("Drop_spDeleteResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteServiceComponent]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[spDeleteServiceComponent]
        ///.
        /// </summary>
        internal static string Drop_spDeleteServiceComponent {
            get {
                return ResourceManager.GetString("Drop_spDeleteServiceComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteServiceDesk]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].spDeleteServiceDesk
        ///.
        /// </summary>
        internal static string Drop_spDeleteServiceDesk {
            get {
                return ResourceManager.GetString("Drop_spDeleteServiceDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteServiceDeskContents]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[spDeleteServiceDeskContents]
        ///GO
        ///.
        /// </summary>
        internal static string Drop_spDeleteServiceDeskContents {
            get {
                return ResourceManager.GetString("Drop_spDeleteServiceDeskContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteServiceDomain]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[spDeleteServiceDomain]
        ///.
        /// </summary>
        internal static string Drop_spDeleteServiceDomain {
            get {
                return ResourceManager.GetString("Drop_spDeleteServiceDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[spDeleteServiceFunction]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[spDeleteServiceFunction]
        ///.
        /// </summary>
        internal static string Drop_spDeleteServiceFunction {
            get {
                return ResourceManager.GetString("Drop_spDeleteServiceFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 26/10/2015
        ///-- Description:	Customer deletion
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[spDeleteCustomer]
        ///	-- Add the parameters for the stored procedure here
        ///	@CustomerId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN TRAN
        ///
        ///		DECLARE @ServiceDeskId int
        ///		DECLARE ServiceDesk_cursor CURS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modify_spDeleteCustomer {
            get {
                return ResourceManager.GetString("Modify_spDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Matt Jordan
        ///-- Create date: 25/10/2016
        ///-- Description:	Service Desk Content Deletion
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[spDeleteServiceDeskContents]
        ///	-- Add the parameters for the stored procedure here
        ///	@ServiceDeskId int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	BEGIN
        ///
        ///		DECLARE @ResolverId int
        ///		DECLARE Resol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modify_spDeleteServiceDeskContents {
            get {
                return ResourceManager.GetString("Modify_spDeleteServiceDeskContents", resourceCulture);
            }
        }
    }
}
