// <auto-generated />
namespace Fujitsu.SLM.Data.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class UserTableAmendments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTableAmendments));
        
        string IMigrationMetadata.Id
        {
            get { return "201502271250334_UserTableAmendments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
