// <auto-generated />
namespace Fujitsu.SLM.Data.Migrations.SLM
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddResolverGroupTypeVisibleColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResolverGroupTypeVisibleColumn));

        string IMigrationMetadata.Id
        {
            get { return "201512160847364_AddResolverGroupTypeVisibleColumn"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
