// <auto-generated />
namespace Fujitsu.SLM.Data.Migrations.SLM
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OperationalProcessTypeRefDataStandardColumnAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OperationalProcessTypeRefDataStandardColumnAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151121211_OperationalProcessTypeRefDataStandardColumnAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
